- name: Install the Nginx RedHat 
  yum:  
   name: nginx  
   state: present  
  when: ansible_os_family == "RedHat"  
  tags: install  

- name: Install the Nginx Debian 
  apt:  
   name: nginx  
   state: present  
  when: ansible_os_family == "Debian"  
  tags: install