---
- hosts: master
  remote_user: root
  become: yes
  gather_facts: no
  
  roles:
   - {role: cluster, server_id: 1}



- hosts: slave
  remote_user: root
  become: yes
  gather_facts: no
  
  roles:
   - {role: cluster, server_id: 2, mysql_replication_role: slave, mysql_replication_master: 34.101.100.223}