---
- hosts: server 
  become: yes
  gather_facts: no
  vars_files:
    - group_vars/vars
  
  tasks:
   - name: Setup Proxy
     apt: name=cobbler state=installed
     environment:
       http_proxy: http://proxy.example.com:80
       https_proxy: http://proxy.example.com:443

  roles:  
   - dbserver
  
  handlers:
    - import_task:
      - handlers/mysql.yml