---
- hosts: onprem-main
  become: yes
  gather_facts: no

  vars:
   - http_env: https_proxy=http://10.0.1.177:80
   - https_env: https_proxy=http://10.0.1.177:443

  roles:
   - single

  environment:
    - http_proxy: "{{ http_env }}"  
    - https_proxy: "{{ https_env }}"  

  