---
- hosts: master
  become: yes
  gather_facts: no

  tasks:
   - name: chmod
     script: chown --reference=/var/lib/mysql /mnt/mysql/data/
    #  args:
    #    chdir: 
    #  with_items:
      
    #   - chmod --reference=/var/lib/mysql /mnt/wikiceria/mysql/data/
  