---
- hosts: master
  remote_user: root
  become: yes
  gather_facts: no
  
  roles:
   - mysql5.7

- hosts: slave
  remote_user: root
  become: yes
  gather_facts: no
  
  roles:
   - {role: mysql5.7, server_id: 2,mysql_replication_role: slave, mysql_replication_master: 34.101.100.223}