---
# tasks file for roles/mysql
- include tasks: installation.yml
- include tasks: setup-user.yml
- include tasks: config-database.yml



# - name: Enable remote login to mysql
#   lineinfile:
#     path: /etc/mysql/mysql.conf.d/mysqld.cnf
#     regexp: '^bind-address'
#     line: 'bind-address = 0.0.0.0'
#     backup: yes
#   notify:
#     - Restart mysql


