---
# tasks file for MySQL
- name: Task name
  stat:
    path: "{{ dbdatadir }}"
  register: register_name

- name: Create a data directory if it does not exist
  become: true      
  file:
    path: "{{ dbdatadir }}"
    state: directory
  when: not register_name.stat.exists

- name: Ansible copy files from a directory to remote server
  copy:
    src: /var/lib/mysql
    dest: "{{ dbdatadir }}"
    owner: root
    group: root
    mode: 0644
    remote_src: true

# - name: Enable remote login to mysql
#   lineinfile:
#     path: /etc/mysql/mysql.conf.d/mysqld.cnf
#     regexp: '^datadir'
#     line: 'datadir = "{{ dbdatadir }}"'
#     backup: yes
#   notify:
#     - Restart mysql


- name: Inserting a line after a pattern in Ansible example 
  lineinfile:
    path: /etc/apparmor.d/tunables/alias
    line: alias /var/lib/mysql/ -> "{{ dbdatadir }}/mysql",
    insertafter: alias*


- name: Enable remote login to mysql
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes
  notify:
    - Restart mysql