---
# tasks file for roles/mysql
- name: Installing Mysql  and dependencies
  package:
   name: "{{item}}"
   state: present
   update_cache: yes
   loop:
    - mysql-server
    - mysql-client 
    - python3-mysqldb
    - libmysqlclient-dev

- name: start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes
