---
# tasks file for mysql-single
- name: Installing Mysql  and dependencies
  package: name={{ item }} state=present update_cache=yes
  with_items:
   - mysql-common
   - mysql-server
   - mysql-client 
   - python3-mysqldb
   - libmysqlclient-dev

- name: copy .my.cnf file with root password credentials
  template: 
    src: .my.cnf.
    dest: ~/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true

- name: 1. set mysql root pass
  mysql_user:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      user: root
      host_all: yes
      password: "{{ mysql_new_root_password }}"
  ignore_errors: yes
#Create User Database    
- name: creating mysql user (medium_post)
  mysql_user:
    name: test
    password: 1234
    priv: '*.*:ALL,GRANT'
    host: '%'
    state: present
  
# - name: 2. disable remote root login
#   mysql_user:
#       login_user: root
#       login_password: "{{ mysql_new_root_password }}"
#       user: root
#       host_all: yes
#       state: absent
#   ignore_errors: yes

- name: 3. remove anonymous users
  mysql_user:
      login_user: root
      login_password: "{{ mysql_new_root_password }}"
      user: ''
      host_all: yes
      state: absent
  ignore_errors: yes

- name: Create `/root/.my.cnf` with root password credentials
  become: yes
  template:
    src:  .my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: 4. remove test database
  mysql_db: 
      login_user: root
      login_password: "{{ mysql_new_root_password }}"
      db: test
      state: absent
  register: remove_testdb
  ignore_errors: yes


- name: creating medium_db
  mysql_db:
    name: "{{db_name}}"
    state: present

- name: Enable remote login to mysql
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes
  notify:
    - Restart mysql service