---
# tasks file for mysql-single
- name: Installing Mysql  and dependencies
  package: name={{ item }} state=present update_cache=yes
  with_items:
   - mysql-common
   - mysql-server
   - mysql-client 
   - python3-mysqldb
   - libmysqlclient-dev

- name: copy .my.cnf file with root password credentials
  template: 
    src: templates/root/.my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true

  # 'localhost' needs to be the last item for idempotency, see
  # http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 