---
# tasks file for mysql-single
- name: Installing Mysql  and dependencies
  package: name={{ item }} state=present update_cache=yes
  with_items:
   - mysql-common
   - mysql-server
   - mysql-client 
   - python3-mysqldb
   - libmysqlclient-dev

- name: copy .my.cnf file with root password credentials
  template: 
    src: templates/root/.my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true

- name: 1. set mysql root pass
  mysql_user:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      user: root
      host_all: yes
      password: "{{ mysql_new_root_password }}"
- name: 2. disable remote root login
  mysql_user:
      login_user: root
      login_password: "{{ mysql_new_root_password }}"
      user: root
      host_all: yes
      state: absent
- name: 3. remove anonymous users
  mysql_user:
      login_user: root
      login_password: "{{ mysql_new_root_password }}"
      user: ''
      host_all: yes
      state: absent
- name: 4. remove test database
  mysql_db: 
      login_user: root
      login_password: "{{ mysql_new_root_password }}"
      db: test
      state: absent
  register: remove_testdb
- name: 4.1 remove test database priviledges
  block:
    - shell: >
        mysql -u root -p{{ mysql_new_root_password }} 
        -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
    - shell: mysql -u root -p{{ mysql_new_root_password }} -e "FLUSH PRIVILEGES"
  when: remove_testdb|changed

#Create User Database    
- name: creating mysql user (medium_post)
  mysql_user:
    name: test
    password: 1234
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: creating medium_db
  mysql_db:
    name: "{{db_name}}"
    state: present

- name: Enable remote login to mysql
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes
  notify:
    - Restart mysql service