---
# tasks file for mysql-single
- name: Installing Mysql  and dependencies
  package: name={{ item }} state=present update_cache=yes
  with_items:
   - mysql-common
   - mysql-server
   - mysql-client 
   - python3-mysqldb
   - libmysqlclient-dev

- name: copy .my.cnf file with root password credentials
  template: 
    src: templates/root/.my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true

  # 'localhost' needs to be the last item for idempotency, see
  # http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: 
    name: "{{ mysql_root_username }}"
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  notify: Restart mysql service

#Create User Database    
- name: creating mysql user (medium_post)
  mysql_user:
    name: test
    password: 1234
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: creating medium_db
  mysql_db:
    name: "{{db_name}}"
    state: present

- name: Enable remote login to mysql
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes
  notify:
    - Restart mysql service