---
# handlers file for roles/mysql
- name: Start mysql
  service:
    name: mysql
    state: started
    enabled: yes
    
- name: Restart mysql
  service:
    name: mysql
    state: restarted

